# Generated by Django 5.1.4 on 2024-12-18 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "organization",
            "0005_alter_organization_email_alter_organization_industry_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("lincense_type", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("quantity", models.IntegerField(default=1)),
                (
                    "owned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.organization",
                    ),
                ),
            ],
        ),
    ]
