# Generated by Django 5.1.4 on 2024-12-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="provider",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="license",
            name="vendor",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
