# Generated by Django 5.1.4 on 2024-12-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0002_license_provider_license_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="license",
            name="lincense_type",
        ),
    ]
