# Generated by Django 5.1.4 on 2024-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_rename_descrption_organization_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="industry",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
