// industries.js

const industries = [
  "Agriculture",
  "Automotive",
  "Banking",
  "Construction",
  "Consumer Goods",
  "Consulting",
  "Education",
  "Energy",
  "Entertainment",
  "Environmental Services",
  "Financial Services",
  "Food & Beverage",
  "Government",
  "Healthcare",
  "Hospitality",
  "Human Resources",
  "Information Technology",
  "Insurance",
  "Legal Services",
  "Logistics & Supply Chain",
  "Manufacturing",
  "Marketing & Advertising",
  "Media & Communications",
  "Mining",
  "Nonprofit Organization Management",
  "Pharmaceuticals",
  "Professional Services",
  "Real Estate",
  "Retail",
  "Telecommunications",
  "Transportation",
  "Travel & Tourism",
  "Utilities",
  "Wholesale Trade",
];

export default industries;
