# Generated by Django 5.1.4 on 2024-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="asset_tag",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="device",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Maintenance", "Maintenance"),
                    ("Retired", "Retired"),
                ],
                default="Active",
                max_length=50,
            ),
        ),
    ]
