# Generated by Django 5.1.4 on 2024-12-09 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="address",
        ),
    ]
