# Generated by Django 5.1.4 on 2024-12-14 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_organization_descrption_organization_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="descrption",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="phone_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
